(()=>{'use strict';
const $=id=>document.getElementById(id);
const V={
  a:[[800,100,1],[1200,130,.76],[2500,180,.38]],
  i:[[310,80,1],[2250,150,.82],[3000,200,.34]],
  u:[[370,90,1],[950,120,.7],[2200,180,.3]],
  e:[[520,95,1],[1900,140,.78],[2700,190,.34]],
  o:[[520,100,1],[850,120,.76],[2500,180,.3]]
};
const K={'は':['h','a'],'ぴ':['p','i'],'ば':['b','a'],'で':['d','e'],'つ':['t','u'],'ゆ':['y','u'],'る':['r','u']};
const C={
  h:[3400,1400,.055,.07],p:[1900,1000,.095,.055],b:[650,450,.075,.06],
  d:[2500,900,.085,.06],t:[3800,1200,.1,.06],s:[5200,1700,.07,.11],
  y:[2300,900,.045,.055],r:[1700,700,.055,.05]
};
const CHORDS={
  C:[48,55,60,64],
  F:[53,60,65,69],
  G7:[55,62,65,71]
};
const H=n=>440*2**((n-69)/12);
let song=null,audio=null,nodes=[],noise=null,raf=0,playback=null;

function decode(raw){let normalized=raw;try{if(!raw.includes('|'))normalized=decodeURIComponent(raw)}catch(_){}const p=normalized.split('|');if(p[0]!=='SC2'||p.length!==4)throw Error('このSongCodeは再生できません');const notes=p[3].split('~').map(x=>{const m=/^([^.]+)\.(\d+(?:\.\d+)?)\.(.*)$/.exec(x);if(!m)throw Error('曲データが壊れています');return{p:m[1],d:+m[2],l:decodeURIComponent(m[3])}});if(!notes.length||notes.some(n=>!Number.isFinite(n.d)||n.d<=0))throw Error('曲データが壊れています');const bpm=+p[2];if(!Number.isFinite(bpm)||bpm<30||bpm>300)throw Error('テンポ情報が不正です');return{title:decodeURIComponent(p[1]),bpm,notes}}
function midi(note){const m=/^([A-G])([#B]?)(\d)$/.exec(note),s={C:0,D:2,E:4,F:5,G:7,A:9,B:11};if(!m)throw Error('音程データが不正です');return(+m[3]+1)*12+s[m[1]]+(m[2]==='#'?1:m[2]==='B'?-1:0)}
const hz=n=>440*2**((midi(n)-69)/12);
function ctx(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}
function envelope(param,start,end,peak,attack=.035,release=.075){param.setValueAtTime(.0001,start);param.linearRampToValueAtTime(peak,Math.min(end,start+attack));param.setValueAtTime(peak,Math.max(start+attack,end-release));param.exponentialRampToValueAtTime(.0001,end)}
function noiseBuffer(a){if(noise)return noise;noise=a.createBuffer(1,a.sampleRate*.35,a.sampleRate);const data=noise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;return noise}
function consonant(kind,start,maxDur,f0){const spec=C[kind];if(!spec)return;const a=ctx(),[freq,bw,level,length]=spec,dur=Math.min(maxDur,length),src=a.createBufferSource(),filter=a.createBiquadFilter(),gain=a.createGain();src.buffer=noiseBuffer(a);filter.type='bandpass';filter.frequency.value=freq;filter.Q.value=Math.max(.7,freq/bw);envelope(gain.gain,start,start+dur,level,.008,.018);src.connect(filter).connect(gain).connect(a.destination);src.start(start);src.stop(start+dur+.01);nodes.push(src);if(['b','d','y','r'].includes(kind)){const pulse=a.createOscillator(),pg=a.createGain();pulse.type='triangle';pulse.frequency.value=f0;envelope(pg.gain,start,start+dur,.045,.01,.02);pulse.connect(pg).connect(a.destination);pulse.start(start);pulse.stop(start+dur+.01);nodes.push(pulse)}}
function vowel(note,start,dur,vowelName){const a=ctx(),end=start+dur,f0=hz(note),osc=a.createOscillator(),warm=a.createOscillator(),body=a.createGain(),warmGain=a.createGain(),sum=a.createGain(),master=a.createGain();osc.type='sawtooth';warm.type='triangle';osc.frequency.value=f0;warm.frequency.value=f0;warmGain.gain.value=.14;envelope(body.gain,start,end,.18,.035,.08);osc.connect(body);warm.connect(warmGain).connect(body);for(const [freq,bw,gain] of(V[vowelName]||V.a)){const filter=a.createBiquadFilter(),formantGain=a.createGain();filter.type='bandpass';filter.frequency.value=freq*1.1;filter.Q.value=Math.max(1,freq/bw);formantGain.gain.value=gain*1.35;body.connect(filter).connect(formantGain).connect(sum)}master.gain.value=.82;sum.connect(master).connect(a.destination);osc.start(start);warm.start(start);osc.stop(end+.02);warm.stop(end+.02);nodes.push(osc,warm)}
function segment(note,start,dur,cons,vow){const lead=Math.min(dur*.16,(C[cons]?.[3]||.035));consonant(cons,start,lead,hz(note));vowel(note,start+Math.min(.014,lead*.25),Math.max(.045,dur-.01),vow)}
function pronunciation(index,label){if([3,9,15,22].includes(index))return[['s','u',.28],['d','e',.72]];if(index===16)return[['d','i',.5],['y','a',.5]];return[[...(K[label]||['h','a']),1]]}
function voice(note,start,dur,label,index){let at=start;for(const [cons,vow,ratio] of pronunciation(index,label)){const part=dur*ratio;segment(note,at,part,cons,vow);at+=part}}
function musicBox(note,start,dur,bus,level=.075){const a=ctx(),gain=a.createGain(),main=a.createOscillator(),shine=a.createOscillator(),shineGain=a.createGain(),end=start+dur;main.type='sine';shine.type='sine';main.frequency.value=H(note);shine.frequency.value=H(note)*2.01;shineGain.gain.value=.28;gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(level,start+.012);gain.gain.exponentialRampToValueAtTime(.0001,end);main.connect(gain);shine.connect(shineGain).connect(gain);gain.connect(bus);main.start(start);shine.start(start);main.stop(end+.02);shine.stop(end+.02);nodes.push(main,shine)}
function padNote(note,start,dur,bus){const a=ctx(),osc=a.createOscillator(),gain=a.createGain(),end=start+dur;osc.type='triangle';osc.frequency.value=H(note);gain.gain.setValueAtTime(.0001,start);gain.gain.linearRampToValueAtTime(.032,start+.18);gain.gain.setValueAtTime(.032,Math.max(start+.18,end-.32));gain.gain.exponentialRampToValueAtTime(.0001,end);osc.connect(gain).connect(bus);osc.start(start);osc.stop(end+.03);nodes.push(osc)}
function bass(note,start,dur,bus){const a=ctx(),osc=a.createOscillator(),gain=a.createGain(),end=start+dur;osc.type='sine';osc.frequency.value=H(note-12);gain.gain.setValueAtTime(.0001,start);gain.gain.linearRampToValueAtTime(.095,start+.035);gain.gain.exponentialRampToValueAtTime(.0001,end);osc.connect(gain).connect(bus);osc.start(start);osc.stop(end+.02);nodes.push(osc)}
function accompaniment(start,beat){const a=ctx(),bus=a.createGain(),filter=a.createBiquadFilter(),compressor=a.createDynamicsCompressor();bus.gain.value=.45;filter.type='lowpass';filter.frequency.value=5200;compressor.threshold.value=-18;compressor.knee.value=14;compressor.ratio.value=3;compressor.attack.value=.006;compressor.release.value=.24;bus.connect(filter).connect(compressor).connect(a.destination);const plan=[[0,'C',2],[2,'C',3],[5,'G7',3],[8,'C',3],[11,'G7',3],[14,'C',3],[17,'F',2],[19,'C',2],[21,'F',3],[24,'C',3],[27,'C',2.5]],order=[0,2,1,3];for(const [offset,name,length]of plan){const chord=CHORDS[name],at=start+offset*beat,dur=length*beat;[chord[0],chord[1],chord[3]].forEach(note=>padNote(note,at,dur,bus));bass(chord[0],at,Math.min(dur,beat*1.8),bus);const steps=Math.ceil(length*2);for(let step=0;step<steps;step++){const note=chord[order[step%order.length]]+24;musicBox(note,at+step*beat*.5,beat*.72,bus,offset>=27?.1:.075)}}musicBox(84,start+27*beat,beat*1.9,bus,.12)}
function clearVisuals(){document.querySelectorAll('[data-note]').forEach(el=>{el.classList.remove('active','sung');el.removeAttribute('aria-current')});$('birdStage').classList.remove('is-singing')}
function highlight(index){document.querySelectorAll('[data-note]').forEach(el=>{const n=+el.dataset.note;el.classList.toggle('active',n===index);el.classList.toggle('sung',n<index);if(n===index)el.setAttribute('aria-current','true');else el.removeAttribute('aria-current')})}
function setPlaying(value){$('play').disabled=value;$('stop').disabled=!value}
function finish(status='再生が終わりました'){cancelAnimationFrame(raf);raf=0;playback=null;nodes=[];setPlaying(false);$('status').textContent=status}
function syncVisuals(){if(!playback)return;const rel=audio.currentTime-playback.origin,{intro,events,melodyEnd,endingEnd}=playback;if(rel<intro){$('status').textContent='伴奏のイントロを再生しています'}else if(rel<melodyEnd){$('birdStage').classList.add('is-singing');$('status').textContent='伴奏と一緒に名前入りの歌を再生しています';let index=0;for(const event of events){if(rel>=event.start)index=event.index;else break}if(playback.activeIndex!==index){highlight(index);playback.activeIndex=index}}else if(rel<endingEnd){document.querySelectorAll('[data-note]').forEach(el=>{el.classList.remove('active');el.classList.add('sung');el.removeAttribute('aria-current')});$('birdStage').classList.remove('is-singing');$('status').textContent='エンディングを再生しています'}else{return finish()}raf=requestAnimationFrame(syncVisuals)}
function stop(){if(!playback)return;nodes.forEach(n=>{try{n.stop()}catch(_){}});nodes=[];cancelAnimationFrame(raf);raf=0;playback=null;clearVisuals();setPlaying(false);$('status').textContent='再生を停止しました'}
function play(){stop();clearVisuals();const a=ctx(),beat=60/song.bpm,intro=2*beat,origin=a.currentTime+.08,events=[];let at=intro;song.notes.forEach((n,index)=>{const sec=beat*n.d;events.push({index,start:at,end:at+sec});if(n.p!=='R')voice(n.p,origin+at,sec*.96,n.l,index);at+=sec});const melodyEnd=at,endingEnd=29.5*beat;accompaniment(origin,beat);playback={origin,intro,events,melodyEnd,endingEnd,activeIndex:-1};setPlaying(true);syncVisuals()}
try{song=decode(location.hash.slice(1));$('title').textContent=song.title;$('meta').textContent=`${song.notes.length}音・テンポ${song.bpm}・オルゴール伴奏つき`;const m=/to (.+)$/i.exec(song.title);if(m){const chars=[...m[1]];const nameParts=$('name').querySelectorAll('[data-note]');nameParts.forEach((el,i)=>el.textContent=chars[i]||'');}$('play').disabled=false;$('play').onclick=play;$('stop').onclick=stop;$('status').textContent='再生ボタンを押してください'}catch(e){$('title').textContent='SongCodeを開けませんでした';$('status').textContent=e.message;$('status').classList.add('error')}
})();
