(()=>{'use strict';
const $=id=>document.getElementById(id),V={a:[[800,90,1],[1200,110,.72],[2500,150,.35]],i:[[300,70,1],[2300,120,.72],[3000,180,.3]],u:[[350,75,1],[900,100,.65],[2200,160,.28]],e:[[500,80,1],[1900,110,.7],[2600,170,.3]],o:[[500,85,1],[800,100,.72],[2500,170,.28]],n:[[280,75,1],[1050,130,.3],[2100,180,.12]]},K={'は':['h','a'],'ぴ':['p','i'],'ば':['b','a'],'で':['d','e'],'つ':['ts','u'],'ゆ':['y','u'],'る':['r','u']};
let song=null,audio=null,nodes=[];
function decode(raw){const p=raw.split('|');if(p[0]!=='SC2'||p.length!==4)throw Error('このSongCodeは再生できません');const notes=p[3].split('~').map(x=>{const f=x.split('.');return{p:f[0],d:+f[1],l:decodeURIComponent(f.slice(2).join('.'))}});if(!notes.length||notes.some(n=>!Number.isFinite(n.d)||n.d<=0))throw Error('曲データが壊れています');return{title:decodeURIComponent(p[1]),bpm:+p[2],notes}}
function midi(note){const m=/^([A-G])([#B]?)(\d)$/.exec(note),s={C:0,D:2,E:4,F:5,G:7,A:9,B:11};if(!m)throw Error('音程データが不正です');return(+m[3]+1)*12+s[m[1]]+(m[2]==='#'?1:m[2]==='B'?-1:0)}
const hz=n=>440*2**((midi(n)-69)/12);function ctx(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}
function env(g,start,end,peak){g.setValueAtTime(.0001,start);g.linearRampToValueAtTime(peak,start+.04);g.setValueAtTime(peak,Math.max(start+.05,end-.07));g.linearRampToValueAtTime(.0001,end)}
function voice(note,start,dur,label){const a=ctx(),[cons,vowel]=K[label]||['h','a'],end=start+dur,f0=hz(note),osc=a.createOscillator(),body=a.createGain(),sum=a.createGain();nodes.push(osc);osc.type='sawtooth';osc.frequency.value=f0;env(body.gain,start,end,.15);osc.connect(body);(V[vowel]||V.a).forEach(([freq,bw,gain])=>{const f=a.createBiquadFilter(),g=a.createGain();f.type='bandpass';f.frequency.value=freq*1.14;f.Q.value=Math.max(1,freq/bw);g.gain.value=gain*1.2;body.connect(f).connect(g).connect(sum)});sum.connect(a.destination);if(cons){const o=a.createOscillator(),g=a.createGain();nodes.push(o);o.type='sawtooth';o.frequency.value=f0;env(g.gain,start,Math.min(end,start+.06),.035);o.connect(g).connect(a.destination);o.start(start);o.stop(Math.min(end,start+.07))}osc.start(start);osc.stop(end+.02)}
function play(){nodes.forEach(n=>{try{n.stop()}catch(_){}});nodes=[];const a=ctx(),origin=a.currentTime+.08;let at=origin;for(const n of song.notes){const sec=60/song.bpm*n.d;if(n.p!=='R')voice(n.p,at,sec*.94,n.l);at+=sec}$('status').textContent='名前入りの歌を再生しています';setTimeout(()=>$('status').textContent='再生が終わりました',(at-origin)*1000+150)}
try{song=decode(location.hash.slice(1));$('title').textContent=song.title;$('meta').textContent=`${song.notes.length}音・テンポ${song.bpm}`;const m=/to (.+)$/i.exec(song.title);if(m)$('name').textContent=m[1];$('play').disabled=false;$('play').onclick=play;$('status').textContent='再生ボタンを押してください'}catch(e){$('title').textContent='SongCodeを開けませんでした';$('status').textContent=e.message;$('status').classList.add('error')}
})();
