(()=>{'use strict';
const $=id=>document.getElementById(id);
const EXAMPLE='SC2|%E3%81%A1%E3%82%87%E3%81%86%E3%81%A1%E3%82%87|112|C4.1.%E3%81%A1~D4.1.%E3%82%87~E4.2.%E3%81%86~E4.1.%E3%81%A1~D4.1.%E3%82%87~C4.2.%E3%81%86~D4.1.%E3%81%AA~E4.1.%E3%81%AE~F4.1.%E3%81%AF~F4.1.%E3%81%AB~F4.1.%E3%81%A8~E4.1.%E3%81%BE~D4.1.%E3%82%8C~C4.2.%E3%83%BC';
let audio=null,stopping=null,playing=false;
const decode=v=>{try{return decodeURIComponent(v)}catch(_){return v}};
function parse(raw){const p=decode(raw.trim().replace(/^#/, '')).split('|');if(p[0]!=='SC2'||p.length<4)throw Error('SC2形式のSongCodeを入力してください。');const bpm=+p[2];if(!Number.isFinite(bpm)||bpm<40||bpm>240)throw Error('BPMは40〜240で指定してください。');const notes=p.slice(3).join('|').split('~').filter(Boolean).map(x=>{const m=/^([A-G](?:#|B)?-?\d+)\.(\d+(?:\.\d+)?)\.(.*)$/.exec(x);if(!m||+m[2]<=0)throw Error('音符データの形式を確認してください。');return{p:m[1],d:+m[2],l:decode(m[3]||'あ')}});if(!notes.length)throw Error('音符がありません。');return{title:decode(p[1])||'無題の曲',bpm,notes}}
function midi(n){const m=/^([A-G])(#|B)?(-?\d+)$/.exec(n),v={C:0,D:2,E:4,F:5,G:7,A:9,B:11};if(!m)throw Error('音程データが不正です。');return(+m[3]+1)*12+v[m[1]]+(m[2]==='#'?1:m[2]==='B'?-1:0)}
const hz=n=>440*2**((midi(n)-69)/12);
function vowel(t){t=t.normalize('NFKC').replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-96));if(/[いきしちにひみりぎじぢびぴ]/.test(t))return'i';if(/[うくすつぬふむゆるぐずづぶぷ]/.test(t))return'u';if(/[えけせてねへめれげぜでべぺ]/.test(t))return'e';if(/[おこそとのほもよろをごぞどぼぽ]/.test(t))return'o';return'a'}
const F={a:[[800,90,1],[1200,110,.72],[2500,150,.35]],i:[[300,70,1],[2300,120,.72],[3000,180,.3]],u:[[350,75,1],[900,100,.65],[2200,160,.28]],e:[[500,80,1],[1900,110,.7],[2600,170,.28]],o:[[500,85,1],[800,100,.72],[2500,170,.28]]};
function stop(){if(audio){audio.close();audio=null}if(stopping)clearTimeout(stopping);stopping=null;playing=false;$('play').textContent='▶ 再生する'}
function show(song){$('songInfo').hidden=false;$('songTitle').textContent=song.title;$('songBpm').textContent='BPM '+song.bpm;$('songNotes').textContent=song.notes.length+' 音';$('songDuration').textContent='約 '+Math.max(1,Math.round(song.notes.reduce((s,n)=>s+n.d,0)*60/song.bpm))+' 秒'}
function get(){try{const s=parse($('code').value);show(s);$('status').className='status';$('status').innerHTML='<span></span>「'+s.title+'」を読み込みました。';return s}catch(e){$('songInfo').hidden=true;$('status').className='status error';$('status').innerHTML='<span></span>'+e.message;return null}}
function play(){const song=get();if(!song)return;if(playing){stop();$('status').innerHTML='<span></span>再生を停止しました。';return}audio=new(window.AudioContext||window.webkitAudioContext)();const out=audio.createGain(),comp=audio.createDynamicsCompressor();out.gain.value=.85;out.connect(comp).connect(audio.destination);let at=audio.currentTime+.07;song.notes.forEach(n=>{const d=Math.max(.06,n.d*60/song.bpm);if(n.p!=='R'){const osc=audio.createOscillator(),g=audio.createGain();osc.type='sawtooth';osc.frequency.value=hz(n.p);g.gain.setValueAtTime(.0001,at);g.gain.linearRampToValueAtTime(.19,at+Math.min(.04,d/3));g.gain.setValueAtTime(.19,Math.max(at+.05,at+d-.07));g.gain.exponentialRampToValueAtTime(.0001,at+d);osc.connect(g);(F[vowel(n.l)]||F.a).forEach(([f,w,level])=>{const filter=audio.createBiquadFilter(),fg=audio.createGain();filter.type='bandpass';filter.frequency.value=f;filter.Q.value=Math.max(1,f/w);fg.gain.value=level;g.connect(filter).connect(fg).connect(out)});osc.start(at);osc.stop(at+d+.03)}at+=d});playing=true;$('play').textContent='■ 停止';$('status').innerHTML='<span></span>「'+song.title+'」を再生しています。';stopping=setTimeout(()=>{stop();$('status').innerHTML='<span></span>再生が終わりました。'},Math.max(0,(at-audio.currentTime)*1000+180)}
function make(){const song=get();if(!song)return;const code='SC2|'+encodeURIComponent(song.title)+'|'+song.bpm+'|'+song.notes.map(n=>n.p+'.'+n.d+'.'+encodeURIComponent(n.l)).join('~');$('code').value=code;const url=location.href.split('#')[0]+'#'+encodeURIComponent(code);QRCode.toDataURL(url,{width:520,margin:2,errorCorrectionLevel:'M'},(e,data)=>{if(e){$('status').className='status error';$('status').innerHTML='<span></span>QRコードを作成できませんでした。';return}$('qr').src=data;$('download').href=data;$('qrArea').hidden=false;$('status').className='status';$('status').innerHTML='<span></span>QRコードを作成しました。画像として保存できます。'})}
$('code').value=location.hash?decode(location.hash.slice(1)):EXAMPLE;$('example').onclick=()=>{$('code').value=EXAMPLE;$('qrArea').hidden=true;get()};$('play').onclick=play;$('make').onclick=make;get();
})();